name: main

on: push

jobs:
  build:
    strategy:
      matrix:
        config:
          - runs-on: ubuntu-20.04
            node-version: '6.11.5' # LTS
            NO_FORMATTED: 1
            NO_LINT: 1
            NPM: 6

          - runs-on: ubuntu-20.04
            node-version: '8.9.0' # LTS
            NO_FORMATTED: 1
            NO_LINT: 1

          - runs-on: ubuntu-20.04
            node-version: '10.13.0' # LTS
            NO_FORMATTED: 1
            NO_LINT: 1

          - runs-on: ubuntu-20.04
            node-version: '12.13.0' # LTS
            NO_FORMATTED: 1
            NO_LINT: 1

          - runs-on: ubuntu-20.04
            node-version: '14.15.0' # LTS
            NO_FORMATTED: 1
            NO_LINT: 1

          - runs-on: ubuntu-20.04
            node-version: '16.13.0' # LTS
            NO_FORMATTED: 1
            NO_LINT: 1

          - runs-on: ubuntu-20.04
            node-version: '16.16.0' # LTS (current)

          - runs-on: ubuntu-20.04
            node-version: '18.5.0'

          - runs-on: windows-2019
            node-version: '18.5.0'

          - runs-on: macos-10.15
            node-version: '18.5.0'

    runs-on: ${{ matrix.config.runs-on }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.config.node-version }}

      - name: NPM 6+
        run: npm install -g npm@6.9.0
        if: matrix.config.NPM == 6

      - name: NPM Version
        run: npm --version

      - name: Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test

      - name: Lint
        run: npm run lint
        if: matrix.config.NO_LINT != 1

      - name: Formatted
        run: npm run formatted
        if: matrix.config.NO_FORMATTED != 1

  publish:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build

    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.16.0'
          registry-url: https://registry.npmjs.org/

      - name: Dependencies
        run: npm ci

      - name: Publish
        run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
